version: '3.8'
services:
  client:
    image: current-24-prod-i
    build: 
      dockerfile: Dockerfile.prod
    container_name: current-24-prod-c
    ports:    
      - "3000:3000"
    environment:
      - NODE_ENV=production
      