version: '3.8'
services:
  client:
    image: currents-24-prod-i
    build: 
      dockerfile: ./currents-24/Dockerfile.prod
    container_name: currents-24-prod-c
    ports:    
      - "3000:3000"
    environment:
      - NODE_ENV=production
      