version: '3.8'
services:
  client:
    image: currents-24-dev-i
    build: 
      dockerfile: ./currents-24/Dockerfile.dev
    container_name: currents-24-dev-c
    volumes:
      - ./currents-24:/currents-24:rw
      - node_modules:/currents-24/node_modules/
    ports:    
      - "8080:8080"
    environment:
      - NODE_ENV=development
volumes:
  node_modules: